{% set name = "resourcecode" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/resourcecode-{{ version }}.tar.gz
  sha256: 5681dc3a02de5375fead8701b55fdba55d458453fb4e3d17dc2a35f7ef6aece2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }},<3.13
    - pandas >=2.2,<3.0
    - requests >=2.31,<3.0
    - numpy >=2.0,<3.0.0
    - scipy >=1.14.1,<2
    - pyextremes >=2.5.0,<3
    - pytest >=7.0.0
    - pyarrow >=18,<19
    - plotly >=6,<7
    - xarray >=2024.11.0
    - netcdf4 >=1.7.0


test:
  imports:
    - resourcecode
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://resourcecode-project.github.io/py-resourcecode/
  dev_url: https://github.com/Resourcecode-project/py-resourcecode
  summary: The ResourceCODE Marine Data Toolbox is a python package to facilitate the access to recent hindcast database of sea-state , along with a set of state-of-the-art methods for data analysis.
  license: GPL-3.0-only
  license_file:
    - COPYING
    - LICENSE

extra:
  recipe-maintainers:
    - NRaillard
